# Generated by Django 5.2.7 on 2025-11-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auction_bid_comment_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.AddField(
            model_name='auction',
            name='categories',
            field=models.ManyToManyField(related_name='auctions', to='auctions.category'),
        ),
    ]
